### ISSUE TITLE
OGR error when using st_transform

### ISSUE THREAD

**Issue by j-galloway** [bcgov/grizzly-bear-status-indicator#9]
https://github.com/bcgov/grizzly-bear-status-indicator/blob/1f1b360f0a2c5187d0f4ac2422f68e324cc279ed/02_clean.R#L22
Returns the following: 
`OGR: Corrupt data
Error in CPL_transform(x, crs$proj4string) : OGR error
In addition: Warning message:
In CPL_crs_from_epsg(as.integer(x)) :
  GDAL Error 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.`
This wasn't happening before - possible change with the GDAL API? (as suggested here: https://github.com/r-spatial/sf/issues/509)

**Comment by ateucher** [comment]
I think you can close this hey @j-galloway?

**Comment by j-galloway** [comment]
Good call, thank @ateucher !
